name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install nvm, node, npm
      uses: dcodeIO/setup-node-nvm@v4

    - name: Install dependencies
      run: make deps
      
    - name: Run build
      run: make
